### ISSUE TITLE
Advanced>edit not saving changes to pokemon 

### ISSUE THREAD

**Issue by eco9898** [kwsch/PKHeX.Mobile#35]
In generation 1, possibly others too, when directly editing a pokemon, via advanced>edit, the changes made aren't applied to the pokemon that was edited. It does open save the pokemon to the active slot, but the feature seems like its meant to directly edit the pokemon that was selected so you dont have to override it afterwards. Otherwise, it just makes more sense to click pop and then edit rather than having this second menu option. Perhaps this should be reworked or removed?

**Comment by kwsch** [comment]
Advanced->Edit only combines the Pop & Edit features to reduce the amount of interactions required.

https://github.com/kwsch/PKHeX.Mobile/blob/b21f2294c5449fa041de7a67670d053533240de9/PKHeX.Mobile/Views/SaveEditor.xaml.cs#L165-L174

The interactions with respect to mobile haven't really been fleshed out since initial development.

**Comment by eco9898** [comment]
As that's the intended feature, I will close this
