### ISSUE TITLE
Error transferring Pokemon from one generation's save to another's

### ISSUE THREAD

**Issue by Gongdong62** [kwsch/PKHeX.Mobile#64]
![Screenshot_20230317-042845](https://user-images.githubusercontent.com/128101977/225771085-5421a66c-c1c1-4e67-8708-3c698de34fb6.jpg)
![Screenshot_20230317-042925](https://user-images.githubusercontent.com/128101977/225771103-7c85d914-0efb-44b7-ba5e-e633a1e300a1.jpg)

I'm trying to transfer this Pokemon from my gen 6 save (name:bonk) to my gen 7 save (name:Jo),everytime I try to do it this error shows up I tried changing ht and ot but it is the same. Any help is appreciated. How should I fix this problem?

**Comment by delipunch** [comment]
This may not be implemented yet, I'm not sure. There are a few things not yet done in this port.

However it's bad practice to title the issue with "please help" or similar since it doesn't make it clear what this particular issue is about from the list of open issues. A better title for this would be "error transferring Pokemon from one generation's save to another's".

**Comment by Gongdong62** [comment]
Thanks for the quick reply. I apologise for naming it like this but couldn't think of anything. This is weird for me because I tried to do it a few weeks back and it worked. But now whenever I try it,it always is illegal. Also,I could be doing something wrong, how would I normally transfer from one gen to another?

Thanks again!

**Comment by kwsch** [comment]
Current handler toggling is not available for GUI changing.

Setting it to the save file will fix it; assuming your save file has different OT/ID details than the transferred Pokémon.
